---

- hosts: etl
  become: yes
  become_user: "{{ etl_user_name }}"

  vars:
    env_name: "{{ inventory_dir | regex_replace('.+/([^/]+)+$', '\\1') }}"
    addon_dir: "{{ playbook_dir }}"

  roles:
    - ask_confirmation
    - load_env_vars
    - addon_role